config:
  prod:
    configdb:
      host: "193.168.3.129"
      user: "postgres"
      password: "W}J}W`PH&n{>x2nf>%[+^Ex=JAX8N^Et~Er"
      dbname: "dev_memory_lane"
  dev:
    configdb:
      host: "localhost"
      user: "postgres"
      password: ""
      dbname: "memory_lane"
  mail:
      Host: "smtp.yandex.ru"
      SMTPAuth: true
      Username: "mailbot@memory-lane.ru"
      Password: "Mailer"
      Port: 465
